#replacement_regex_txt : []
#replacement_regex_spdx : []

# # Generaly we do not need to set the package_name and package_version. It will be taken from files name but 
# # in case there is a hash in file name, we need to set these two parameters and remove any other old packages from input folder.
# package_name : ZZZZZ
# package_version : VVVVV

# # In case you would like to clean your output folder before generation of files,
# # set this configuration to true
# remove_output : true

# # One can set the download link set in read me directly here
# download_link : Download_link

# # you can add reviewer here
# reviewer : YYYY

# # You should replace xxxx with your name and uncomment the next line
# creator_name : XXXX
